# Generated by Django 5.0 on 2023-12-27 10:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('pswd', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='WorkSpace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(max_length=500)),
                ('generated_text', models.TextField(max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('video_url', models.URLField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.user')),
            ],
        ),
        migrations.CreateModel(
            name='Uploadfiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('segment_url_1', models.URLField(blank=True, null=True)),
                ('segment_url_2', models.URLField(blank=True, null=True)),
                ('segment_url_3', models.URLField(blank=True, null=True)),
                ('segment_url_4', models.URLField(blank=True, null=True)),
                ('segment_url_5', models.URLField(blank=True, null=True)),
                ('segment_url_6', models.URLField(blank=True, null=True)),
                ('segment_url_7', models.URLField(blank=True, null=True)),
                ('segment_url_8', models.URLField(blank=True, null=True)),
                ('segment_url_9', models.URLField(blank=True, null=True)),
                ('segment_text_1', models.TextField(blank=True, max_length=500, null=True)),
                ('segment_text_2', models.TextField(blank=True, max_length=500, null=True)),
                ('segment_text_3', models.TextField(blank=True, max_length=500, null=True)),
                ('segment_text_4', models.TextField(blank=True, max_length=500, null=True)),
                ('segment_text_5', models.TextField(blank=True, max_length=500, null=True)),
                ('segment_text_6', models.TextField(blank=True, max_length=500, null=True)),
                ('segment_text_7', models.TextField(blank=True, max_length=500, null=True)),
                ('segment_text_8', models.TextField(blank=True, max_length=500, null=True)),
                ('segment_text_9', models.TextField(blank=True, max_length=500, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.user')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.workspace')),
            ],
        ),
    ]
