# Generated by Django 4.2.8 on 2023-12-26 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_rename_segment_url_1_uploadfiles_segment_video_1_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='uploadfiles',
            old_name='segment_video_1',
            new_name='segment_url_1',
        ),
        migrations.RenameField(
            model_name='uploadfiles',
            old_name='segment_video_2',
            new_name='segment_url_2',
        ),
        migrations.RenameField(
            model_name='uploadfiles',
            old_name='segment_video_3',
            new_name='segment_url_3',
        ),
        migrations.RenameField(
            model_name='uploadfiles',
            old_name='segment_video_4',
            new_name='segment_url_4',
        ),
        migrations.RenameField(
            model_name='uploadfiles',
            old_name='segment_video_5',
            new_name='segment_url_5',
        ),
        migrations.RenameField(
            model_name='uploadfiles',
            old_name='segment_video_6',
            new_name='segment_url_6',
        ),
        migrations.RenameField(
            model_name='uploadfiles',
            old_name='segment_video_7',
            new_name='segment_url_7',
        ),
        migrations.RenameField(
            model_name='uploadfiles',
            old_name='segment_video_8',
            new_name='segment_url_8',
        ),
        migrations.RenameField(
            model_name='uploadfiles',
            old_name='segment_video_9',
            new_name='segment_url_9',
        ),
    ]
