# Generated by Django 4.2.8 on 2024-01-01 06:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_rename_segment_video_1_uploadfiles_segment_url_1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Segment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(blank=True, null=True)),
                ('text', models.TextField(blank=True, max_length=500, null=True)),
                ('uploadfile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.uploadfiles')),
            ],
        ),
        migrations.AddField(
            model_name='uploadfiles',
            name='segments',
            field=models.ManyToManyField(to='myapp.segment'),
        ),
    ]
