# Generated by Django 4.2.8 on 2024-01-03 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_segment_uploadfiles_segments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadfiles',
            name='segments',
        ),
        migrations.AddField(
            model_name='uploadfiles',
            name='upload_file_1',
            field=models.FileField(blank=True, null=True, upload_to='Uploaded_files'),
        ),
        migrations.AddField(
            model_name='uploadfiles',
            name='upload_file_2',
            field=models.FileField(blank=True, null=True, upload_to='Uploaded_files'),
        ),
        migrations.AddField(
            model_name='uploadfiles',
            name='upload_file_3',
            field=models.FileField(blank=True, null=True, upload_to='Uploaded_files'),
        ),
        migrations.DeleteModel(
            name='Segment',
        ),
    ]
