# Generated by Django 4.2.8 on 2024-01-03 06:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_remove_uploadfiles_segments_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadfiles',
            name='upload_file_1',
        ),
        migrations.RemoveField(
            model_name='uploadfiles',
            name='upload_file_2',
        ),
        migrations.RemoveField(
            model_name='uploadfiles',
            name='upload_file_3',
        ),
    ]
