# Generated by Django 4.2.8 on 2024-01-04 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_remove_uploadfiles_upload_file_1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadfiles',
            name='uploaded_file_path',
            field=models.FileField(blank=True, null=True, upload_to='uploaded_files/'),
        ),
        migrations.AddField(
            model_name='workspace',
            name='uploaded_file_path',
            field=models.FileField(blank=True, null=True, upload_to='uploaded_files/'),
        ),
    ]
