# Generated by Django 4.2.8 on 2024-01-09 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_remove_uploadfiles_uploaded_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadfiles',
            name='edited_video',
            field=models.FileField(blank=True, null=True, upload_to='videos/'),
        ),
    ]
